//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public int Id { get; set; }
        public int NumProduct { get; set; }
        public string Title { get; set; }
        public Nullable<double> Mass { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
    }
}
